
package com.example.hrms.ksp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KPSPublicSoap", targetNamespace = "http://tckimlik.nvi.gov.tr/WS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KPSPublicSoap {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.yildizholding.ocean.hrpbordromendix.ksp.TCKimlikNoDogrulaResponse
     */
    @WebMethod(operationName = "TCKimlikNoDogrula", action = "http://tckimlik.nvi.gov.tr/WS/TCKimlikNoDogrula")
    @WebResult(name = "TCKimlikNoDogrulaResponse", targetNamespace = "http://tckimlik.nvi.gov.tr/WS", partName = "parameters")
    public TCKimlikNoDogrulaResponse tcKimlikNoDogrula(
        @WebParam(name = "TCKimlikNoDogrula", targetNamespace = "http://tckimlik.nvi.gov.tr/WS", partName = "parameters")
        TCKimlikNoDogrula parameters);

}
